
const actionTypes = {
    CURRENTUSER: 'CURRENTUSER',
    USERUID: 'USERUID',
    USERDETAIL: 'USERDETAIL',
    EVENTS: 'EVENTS',
    GOING: 'GOING',
    ARRAY: 'ARRAY',
    NOTGOING: 'NOTGOING',
    EVENTS: 'EVENTS',
    TOTALSEATS: 'TOTALSEATS',
    CARD: 'CARD',
    TOTALRESERVED: 'TOTALRESERVED',
    LIST: 'LIST',
    RESERVEDSEATS: 'RESERVEDSEATS'
}

export default actionTypes